### ISSUE TITLE
[Feature request] "all tabs list"

### ISSUE THREAD

**Issue by LeGiTiM** [nvgtx/tab-focus#1]
Hi,
I'm not familiar with github, I hope this is the good section to submit a request.
Could you consider making this addon work on the "all tabs list" of firefox? (when you have too many tabs, you can click a button to display a list of all tabs).
I desperately searched for an addon to create a gallery of previews of all tabs, but if your addon could allow me to preview each of them by hovering them on this list, that would do the trick. It would be awesome!
Whatever you decide to do, thank you for the hard work and consideration. Your addon is really appreciated. ;)

**Comment by nvgtx** [comment]
At least I've now found the corresponding menu definition in the FF source - remains to be seen whether I can get a useful tabbrowser object from it...
browser.xul:
`<toolbarbutton id="alltabs-button" class="toolbarbutton-1 chromeclass-toolbar-additional tabs-alltabs-button" type="menu" label="&listAllTabs.label;" tooltiptext="&listAllTabs.label;" removable="false">
    <menupopup id="alltabs-popup" position="after_end">
        <menuitem id="alltabs_undoCloseTab" class="menuitem-iconic" key="key_undoCloseTab" label="&undoCloseTab.label;" observes="History:UndoCloseTab"/>
        <menuseparator id="alltabs-popup-separator-1" />
        <menu id="alltabs_containersTab" label="&newUserContext.label;">
            <menupopup id="alltabs_containersMenuTab" />
        </menu>
        <menuseparator id="alltabs-popup-separator-2" />
    </menupopup>
</toolbarbutton>`

**Comment by nvgtx** [comment]
Sadly, due to Mozillas decision to drop support for the Addon-SDK and only supporting WebExtensions as programming interface, this addon will cease working with release of Firefox 57.
The current Addon-SDK of Firefox does not support your requested functionality, WebExtensions do not even provide the required functionality to make this addon work in the first place.
Sorry.
