### ISSUE TITLE
Tab Focus 2.0.3 preview mode compatibility with Tab Groups 2.1.4

### ISSUE THREAD

**Issue by grahamperrin** [nvgtx/tab-focus#3]
Tested with Waterfox 56.0.1 on FreeBSD-CURRENT. Preview mode enabled. 

If I use the Tab Groups menu to switch to a different group (or expand a group and switch to a particular tab): it seems that Tab Focus will then cause a switch back to the previously active tab (in the previously active group).

**Comment by nvgtx** [comment]
Hi,
the preview mode stores the reference of the current selected tab on a mouse click event on said tab. On a mouse-out event it switches to that stored tab.
I'm not sure whether that function is particularly useful when used in conjunction with an addon like tab groups - have you tried it with preview mode disabled?

**Comment by nvgtx** [comment]
In the end Tab Focus has no idea about the hierarchy of tabs (the grouping) as this is not existent in the base browser code and only introduced by the other addon.
As such it does not care on how the tabs are structured/grouped, nor can it properly compensate for it. This can only be done (properly) by the addon with changed the structure.

**Comment by grahamperrin** [comment]
> …  have you tried it with preview mode disabled?

Yes, no problem.

**Comment by nvgtx** [comment]
Ok, if its alright for you, I'll mark this as WONTFIX because one would have to merge the two addons into one in order to properly resolve this.
